version: "3.2"
services:
  mongo:
    image: mongo
    restart: always
    networks:
      - main
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: PASSWORD
    # volumes:
    # - /Volumes/mongo/data/db:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - main
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: PASSWORD
  instabot:
    restart: always
    networks:
      - main
    build: "./"
    environment:
      STORAGE_URL: "mongodb://root:PASSWORD@mongo:27017"
      STORAGE_DB_NAME: "instabot"
      STORAGE_COLLECTION_NAME: "followed_by_stamps"
      BOT_USERNAME: ""
      BOT_EMAIL: "name@example.com"
      BOT_PASSWORD: "PASSWORD"
      TARGET_USERNAME: "foxystyle774"
networks:
  main:
